global_frame: odom
rolling_window: true
update_frequency: 10.0
publish_frequency: 10.0
resolution: 0.1
transform_tolerance: 0.5

plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}